###   3-Example  -    Dockerfile - Setting  Environment variables    
#################################         START     ################ ############

## Here the  base image is alpine and Tag (version) is 3.12 

FROM alpine:3.12  
RUN apk add  curl
RUN apk add nano

### Defining or Setting Environment variables

ENV X=10
ENV CITY=Austin-Texas
ENV STATE=New Jersey

#################################         END       #############################
